# Generated by Django 2.2 on 2019-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190528_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(auto_created=True),
        ),
    ]
