# Generated by Django 2.2 on 2019-05-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20190529_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('electronics', 'Electronicos'), ('sports', 'Deportes'), ('other', 'Miscelaneos')], default='Deportes', max_length=50),
        ),
    ]
