# Generated by Django 2.2 on 2019-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_auto_20190529_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('electronics', 'Electrónicos'), ('sports', 'Deportes'), ('other', 'Misceláneos')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=10.99),
        ),
    ]
