# Generated by Django 2.2 on 2019-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_auto_20190529_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
